version: '3'
services:
  app:
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./app:/var/www/html/app
    tty: true